### ISSUE TITLE
"Failed to Initialize" after updating to v0.9.3

### ISSUE THREAD

**Issue by tasinclair4** [ufodone/envisalink_new#153]
Tried reloading after restart, then restarted again.

Currently on core-2024.10.4

Ended up restoring to last backup and all is well on v0.9.2

**Comment by ufodone** [comment]
Hmm.. I suspect that the changes in HA core that caused the deprecation warnings in this integration (#151) also introduced what was needed to fix them.  So my guess is the failure you are seeing is due to an incompatibility between 0.9.3+ and HA core versions prior to 2024.11.1.  

If you have any logs from the failures, I could confirm this theory but based on when the changes were made in HA core, it's likely this is the issue.

If the problem persists after you upgrade to 2024.11, please attach some logs with the errors.

**Comment by mtuska** [comment]
I've received the same issue upgrading from v0.9.2 to v0.9.4, here are my details.

Core
2024.9.2
Frontend
20240909.1

ERROR:
```
Logger: homeassistant.config_entries
Source: config_entries.py:604
First occurred: 8:51:24 PM (1 occurrences)
Last logged: 8:51:24 PM

Error setting up entry Alarm for envisalink_new
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/envisalink_new/__init__.py", line 149, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 2108, in async_forward_entry_setups
    await integration.async_get_platforms(platforms)
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1177, in async_get_platforms
    import_future.result()
  [Previous line repeated 2 more times]
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1165, in async_get_platforms
    platforms.update(self._load_platforms(platform_names))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1090, in _load_platforms
    platform_name: self._load_platform(platform_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1264, in _load_platform
    cache[full_name] = self._import_platform(platform_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 1296, in _import_platform
    return importlib.import_module(f"{self.pkg_path}.{platform_name}")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/util/loop.py", line 200, in protected_loop_func
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/config/custom_components/envisalink_new/alarm_control_panel.py", line 6, in <module>
    from homeassistant.components.alarm_control_panel import (
ImportError: cannot import name 'AlarmControlPanelState' from 'homeassistant.components.alarm_control_panel' (/usr/src/homeassistant/homeassistant/components/alarm_control_panel/__init__.py)
```

WARNING:
```
Logger: homeassistant.util.loop
Source: util/loop.py:136
First occurred: 8:51:24 PM (1 occurrences)
Last logged: 8:51:24 PM

Detected blocking call to import_module with args ('custom_components.envisalink_new.alarm_control_panel',) inside the event loop by custom integration 'envisalink_new' at custom_components/envisalink_new/__init__.py, line 149: await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS) (offender: /usr/src/homeassistant/homeassistant/loader.py, line 1296: return importlib.import_module(f"{self.pkg_path}.{platform_name}")), please create a bug report at https://github.com/ufodone/envisalink_new/issues For developers, please see https://developers.home-assistant.io/docs/asyncio_blocking_operations/#import_module Traceback (most recent call last): File "<frozen runpy>", line 198, in _run_module_as_main File "<frozen runpy>", line 88, in _run_code File "/usr/src/homeassistant/homeassistant/__main__.py", line 223, in <module> sys.exit(main()) File "/usr/src/homeassistant/homeassistant/__main__.py", line 209, in main exit_code = runner.run(runtime_conf) File "/usr/src/homeassistant/homeassistant/runner.py", line 189, in run return loop.run_until_complete(setup_and_run_hass(runtime_config)) File "/usr/local/lib/python3.12/asyncio/base_events.py", line 674, in run_until_complete self.run_forever() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 641, in run_forever self._run_once() File "/usr/local/lib/python3.12/asyncio/base_events.py", line 1990, in _run_once handle._run() File "/usr/local/lib/python3.12/asyncio/events.py", line 88, in _run self._context.run(self._callback, *self._args) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 752, in async_setup_locked await self.async_setup(hass, integration=integration) File "/usr/src/homeassistant/homeassistant/config_entries.py", line 604, in async_setup result = await component.async_setup_entry(hass, self) File "/config/custom_components/envisalink_new/__init__.py", line 149, in async_setup_entry await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
```

**Comment by ufodone** [comment]
```
ImportError: cannot import name 'AlarmControlPanelState'
```

Yes, that's definitely due to to those older versions of HA core not having the needed changes.  Apologies for not realizing these releases required a 2024.11 HA core release.  I'll try and update the release notes.

**Comment by bassdr** [comment]
Yep, I had that too. IMO we should have kept the deprecation warnings for a while. I usually keep the last version of last month on my non-dev setups, they tend to have much less bugs.
