### ISSUE TITLE
Error adding entities for domain binary_sensor with platform envisalink_new

### ISSUE THREAD

**Issue by garyak** [ufodone/envisalink_new#73]
Installed 7.3. Got multiple instances (2) of this error in the HA log:
```
2023-12-01 14:47:01.689 ERROR (MainThread) [homeassistant.components.binary_sensor] Error adding entities for domain binary_sensor with platform envisalink_new
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 752, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1023, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 743, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 843, in _async_write_ha_state
    state, attr = self._async_generate_attributes()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 787, in _async_generate_attributes
    attr.update(self.extra_state_attributes or {})
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/envisalink_new/binary_sensor.py", line 98, in extra_state_attributes
    last_fault = self.last_state.attributes.get(ATTR_LAST_TRIP_TIME)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'attributes'
```
Downgraded to 7.2.

**Comment by ufodone** [comment]
Sorry about that.  I've published a new release which I think will fix the issue.

**Comment by garyak** [comment]
No error in HA log on restart with 7.4
